# Generated by Django 5.2 on 2025-08-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_test_description_remove_test_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='seen_instructions',
            field=models.BooleanField(default=False),
        ),
    ]
